### ISSUE TITLE
Crashes if no country code provided

### ISSUE THREAD

**Issue by thherman** [TercyoStorck/internationalization#3]
If we add a Locale without country code, such as `Locale('en')` for default English, the library is looking for `en_null.json` instead of `en.json` which should be the intended behaviour if I am correct.

It would be quite simple to fix by checking if the country code is null before looking for the resource! For example, in method `_load`:

```dart
String localeFile = this._locale.countryCode == null  
        ? '${this._path}/${this._locale.languageCode}.json'  
        : '${this._path}/${this._locale.languageCode}_${this._locale.countryCode}.json;'  
String data = await rootBundle.loadString(localeFile);
```

The same can be applied in method `_loadDefault`.

**Comment by TercyoStorck** [comment]
Now it's supported. Thank you =)
