### ISSUE TITLE
including this package in latest dart does not work

### ISSUE THREAD

**Issue by triankar** [TercyoStorck/internationalization#6]
my pubspec.yaml contains
  internationalization: ^3.0.1+1

When I run pub get, the output is:
Because every version of internationalization depends on flutter_localizations any from sdk which depends on intl 0.17.0, every version of internationalization requires intl 0.17.0.
So, because dmk_mobile depends on internationalization ^3.0.1+1 which depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because dmk_mobile depends on internationalization ^3.0.1+1 which depends on intl ^0.16.1, version solving failed.)
Process finished with exit code 1

**Comment by mregnauld** [comment]
Same problem here. Any fix?

**Comment by TercyoStorck** [comment]
Updated!
